#!"F:\xampp\perl\bin\perl.exe"

$message= <<"END_OF_MESSAGE";
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>Calculator App</title>
<link rel="stylesheet" href="styles.css">
</head>
<body>
<h1>Calculator App</h1>
<form action='calcresult.cgi' method='get' name="calculator">
<label for="a">Operand 1</label>
<input type="text" name="a" required pattern="\\d+">
<label for="b">Operand 2</label>
<input type="text" name="b" required pattern="\\d+">
<label for="method">Operator</label>
<select name="method" >
<option value="add" selected>+</option>
<option value="sub">-</option>
<option value="mul">*</option>
<option value="div">/</option>
</select>
<input type='submit' value='calculate'>
</form>
</body>
</html>


END_OF_MESSAGE

print "Content-type: text/html";
#print "Content-length: ".length $message;
print "\r\n\r\n";
print $message;


